### ISSUE TITLE
fix: redirection does not trigger for GoCardless payments

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp-per-form-confirmations#7] opened 2020-05-22 19:46 UTC
Custom redirection does not work for GoCardless payments.  It always redirects to the general Donation Confirmation page.

![Screen-Shot-2020-05-22-at-2 42 14-PM](https://user-images.githubusercontent.com/312000/82704276-cd9ee400-9c3a-11ea-9939-cb0aa59bcbaf.jpg)

Related: https://secure.helpscout.net/conversation/1158446833/64867?folderId=3400524

**Comment by mathetos** [comment] 2020-06-26 16:54
Duplicate of #6

**Closed by mathetos** 2020-06-26 16:54 UTC
